development:
  dialect: "postgres"
  database: "gotrue_development"
  host: {{ envOr "POSTGRESQL_HOST" "127.0.0.1"  }}
  port: {{ envOr "POSTGRESQL_PORT" "5432"  }}
  user: {{ envOr "POSTGRESQL_USER"  "postgres"  }}
  password: {{ envOr "POSTGRESQL_PASSWORD"  ""  }}

test:
  dialect: "postgres"
  database: "gotrue_test"
  host: {{ envOr "POSTGRESQL_HOST" "127.0.0.1"  }}
  port: {{ envOr "POSTGRESQL_PORT" "5432"  }}
  user: {{ envOr "POSTGRESQL_USER"  "postgres"  }}
  password: {{ envOr "POSTGRESQL_PASSWORD"  ""  }}
